language: cpp
compiler:
- g++
os:
- linux


before_install:
- echo $LANG
- echo $LC_ALL
- sudo apt-get install -y g++
- sudo apt-get update
before_script:
- make
- cd tests 
script: 
  python test.py
branches:
  only:
  - master
env:
  global:
  - LANG="en_US.UTF-8"
  

