language: cpp
compiler:
- g++
os:
- linux

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5


before_install:
- echo $LANG
- echo $LC_ALL
- sudo apt-get update
- sudo apt-get install -y g++
before_script:
- make
- cd tests 
- g++ --versio
script: 
  python test.py
branches:
  only:
  - master
env:
  global:
  - LANG="en_US.UTF-8"
  

