language: cpp
compiler:
- g++
os:
- linux



before_install:
- echo $LANG
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- echo $LC_ALL
- sudo apt-get update -qq
install:
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8"

before_script:
- make
- cd tests 
script: 
  python test.py
branches:
  only:
  - master
env:
  global:
  - LANG="en_US.UTF-8"
  

