# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dumitru/httpserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dumitru/httpserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dumitru/httpserver/CMakeFiles /home/dumitru/httpserver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dumitru/httpserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named httpserver_test

# Build rule for target.
httpserver_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 httpserver_test
.PHONY : httpserver_test

# fast build rule for target.
httpserver_test/fast:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/build
.PHONY : httpserver_test/fast

#=============================================================================
# Target rules for targets named httpserver

# Build rule for target.
httpserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 httpserver
.PHONY : httpserver

# fast build rule for target.
httpserver/fast:
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/build
.PHONY : httpserver/fast

#=============================================================================
# Target rules for targets named googletest

# Build rule for target.
googletest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 googletest
.PHONY : googletest

# fast build rule for target.
googletest/fast:
	$(MAKE) -f ext/gtest/CMakeFiles/googletest.dir/build.make ext/gtest/CMakeFiles/googletest.dir/build
.PHONY : googletest/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/main.cpp.s
.PHONY : main.cpp.s

src/HttpApplication.o: src/HttpApplication.cpp.o

.PHONY : src/HttpApplication.o

# target to build an object file
src/HttpApplication.cpp.o:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpApplication.cpp.o
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpApplication.cpp.o
.PHONY : src/HttpApplication.cpp.o

src/HttpApplication.i: src/HttpApplication.cpp.i

.PHONY : src/HttpApplication.i

# target to preprocess a source file
src/HttpApplication.cpp.i:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpApplication.cpp.i
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpApplication.cpp.i
.PHONY : src/HttpApplication.cpp.i

src/HttpApplication.s: src/HttpApplication.cpp.s

.PHONY : src/HttpApplication.s

# target to generate assembly for a file
src/HttpApplication.cpp.s:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpApplication.cpp.s
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpApplication.cpp.s
.PHONY : src/HttpApplication.cpp.s

src/HttpClient.o: src/HttpClient.cpp.o

.PHONY : src/HttpClient.o

# target to build an object file
src/HttpClient.cpp.o:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpClient.cpp.o
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpClient.cpp.o
.PHONY : src/HttpClient.cpp.o

src/HttpClient.i: src/HttpClient.cpp.i

.PHONY : src/HttpClient.i

# target to preprocess a source file
src/HttpClient.cpp.i:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpClient.cpp.i
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpClient.cpp.i
.PHONY : src/HttpClient.cpp.i

src/HttpClient.s: src/HttpClient.cpp.s

.PHONY : src/HttpClient.s

# target to generate assembly for a file
src/HttpClient.cpp.s:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpClient.cpp.s
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpClient.cpp.s
.PHONY : src/HttpClient.cpp.s

src/HttpMessage.o: src/HttpMessage.cpp.o

.PHONY : src/HttpMessage.o

# target to build an object file
src/HttpMessage.cpp.o:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpMessage.cpp.o
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpMessage.cpp.o
.PHONY : src/HttpMessage.cpp.o

src/HttpMessage.i: src/HttpMessage.cpp.i

.PHONY : src/HttpMessage.i

# target to preprocess a source file
src/HttpMessage.cpp.i:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpMessage.cpp.i
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpMessage.cpp.i
.PHONY : src/HttpMessage.cpp.i

src/HttpMessage.s: src/HttpMessage.cpp.s

.PHONY : src/HttpMessage.s

# target to generate assembly for a file
src/HttpMessage.cpp.s:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpMessage.cpp.s
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpMessage.cpp.s
.PHONY : src/HttpMessage.cpp.s

src/HttpRequest.o: src/HttpRequest.cpp.o

.PHONY : src/HttpRequest.o

# target to build an object file
src/HttpRequest.cpp.o:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpRequest.cpp.o
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpRequest.cpp.o
.PHONY : src/HttpRequest.cpp.o

src/HttpRequest.i: src/HttpRequest.cpp.i

.PHONY : src/HttpRequest.i

# target to preprocess a source file
src/HttpRequest.cpp.i:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpRequest.cpp.i
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpRequest.cpp.i
.PHONY : src/HttpRequest.cpp.i

src/HttpRequest.s: src/HttpRequest.cpp.s

.PHONY : src/HttpRequest.s

# target to generate assembly for a file
src/HttpRequest.cpp.s:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpRequest.cpp.s
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpRequest.cpp.s
.PHONY : src/HttpRequest.cpp.s

src/HttpResponse.o: src/HttpResponse.cpp.o

.PHONY : src/HttpResponse.o

# target to build an object file
src/HttpResponse.cpp.o:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpResponse.cpp.o
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpResponse.cpp.o
.PHONY : src/HttpResponse.cpp.o

src/HttpResponse.i: src/HttpResponse.cpp.i

.PHONY : src/HttpResponse.i

# target to preprocess a source file
src/HttpResponse.cpp.i:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpResponse.cpp.i
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpResponse.cpp.i
.PHONY : src/HttpResponse.cpp.i

src/HttpResponse.s: src/HttpResponse.cpp.s

.PHONY : src/HttpResponse.s

# target to generate assembly for a file
src/HttpResponse.cpp.s:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpResponse.cpp.s
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpResponse.cpp.s
.PHONY : src/HttpResponse.cpp.s

src/HttpServer.o: src/HttpServer.cpp.o

.PHONY : src/HttpServer.o

# target to build an object file
src/HttpServer.cpp.o:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpServer.cpp.o
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpServer.cpp.o
.PHONY : src/HttpServer.cpp.o

src/HttpServer.i: src/HttpServer.cpp.i

.PHONY : src/HttpServer.i

# target to preprocess a source file
src/HttpServer.cpp.i:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpServer.cpp.i
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpServer.cpp.i
.PHONY : src/HttpServer.cpp.i

src/HttpServer.s: src/HttpServer.cpp.s

.PHONY : src/HttpServer.s

# target to generate assembly for a file
src/HttpServer.cpp.s:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/HttpServer.cpp.s
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/HttpServer.cpp.s
.PHONY : src/HttpServer.cpp.s

src/Logger.o: src/Logger.cpp.o

.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/Logger.cpp.o
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i

.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/Logger.cpp.i
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s

.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/Logger.cpp.s
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/RequestHandler.o: src/RequestHandler.cpp.o

.PHONY : src/RequestHandler.o

# target to build an object file
src/RequestHandler.cpp.o:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/RequestHandler.cpp.o
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/RequestHandler.cpp.o
.PHONY : src/RequestHandler.cpp.o

src/RequestHandler.i: src/RequestHandler.cpp.i

.PHONY : src/RequestHandler.i

# target to preprocess a source file
src/RequestHandler.cpp.i:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/RequestHandler.cpp.i
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/RequestHandler.cpp.i
.PHONY : src/RequestHandler.cpp.i

src/RequestHandler.s: src/RequestHandler.cpp.s

.PHONY : src/RequestHandler.s

# target to generate assembly for a file
src/RequestHandler.cpp.s:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/RequestHandler.cpp.s
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/RequestHandler.cpp.s
.PHONY : src/RequestHandler.cpp.s

src/socket.o: src/socket.cpp.o

.PHONY : src/socket.o

# target to build an object file
src/socket.cpp.o:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/socket.cpp.o
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/socket.cpp.o
.PHONY : src/socket.cpp.o

src/socket.i: src/socket.cpp.i

.PHONY : src/socket.i

# target to preprocess a source file
src/socket.cpp.i:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/socket.cpp.i
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/socket.cpp.i
.PHONY : src/socket.cpp.i

src/socket.s: src/socket.cpp.s

.PHONY : src/socket.s

# target to generate assembly for a file
src/socket.cpp.s:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/src/socket.cpp.s
	$(MAKE) -f CMakeFiles/httpserver.dir/build.make CMakeFiles/httpserver.dir/src/socket.cpp.s
.PHONY : src/socket.cpp.s

test/httpclienttest.o: test/httpclienttest.cpp.o

.PHONY : test/httpclienttest.o

# target to build an object file
test/httpclienttest.cpp.o:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/test/httpclienttest.cpp.o
.PHONY : test/httpclienttest.cpp.o

test/httpclienttest.i: test/httpclienttest.cpp.i

.PHONY : test/httpclienttest.i

# target to preprocess a source file
test/httpclienttest.cpp.i:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/test/httpclienttest.cpp.i
.PHONY : test/httpclienttest.cpp.i

test/httpclienttest.s: test/httpclienttest.cpp.s

.PHONY : test/httpclienttest.s

# target to generate assembly for a file
test/httpclienttest.cpp.s:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/test/httpclienttest.cpp.s
.PHONY : test/httpclienttest.cpp.s

test/httprequesttest.o: test/httprequesttest.cpp.o

.PHONY : test/httprequesttest.o

# target to build an object file
test/httprequesttest.cpp.o:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/test/httprequesttest.cpp.o
.PHONY : test/httprequesttest.cpp.o

test/httprequesttest.i: test/httprequesttest.cpp.i

.PHONY : test/httprequesttest.i

# target to preprocess a source file
test/httprequesttest.cpp.i:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/test/httprequesttest.cpp.i
.PHONY : test/httprequesttest.cpp.i

test/httprequesttest.s: test/httprequesttest.cpp.s

.PHONY : test/httprequesttest.s

# target to generate assembly for a file
test/httprequesttest.cpp.s:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/test/httprequesttest.cpp.s
.PHONY : test/httprequesttest.cpp.s

test/test.o: test/test.cpp.o

.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) -f CMakeFiles/httpserver_test.dir/build.make CMakeFiles/httpserver_test.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... httpserver_test"
	@echo "... httpserver"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... googletest"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/HttpApplication.o"
	@echo "... src/HttpApplication.i"
	@echo "... src/HttpApplication.s"
	@echo "... src/HttpClient.o"
	@echo "... src/HttpClient.i"
	@echo "... src/HttpClient.s"
	@echo "... src/HttpMessage.o"
	@echo "... src/HttpMessage.i"
	@echo "... src/HttpMessage.s"
	@echo "... src/HttpRequest.o"
	@echo "... src/HttpRequest.i"
	@echo "... src/HttpRequest.s"
	@echo "... src/HttpResponse.o"
	@echo "... src/HttpResponse.i"
	@echo "... src/HttpResponse.s"
	@echo "... src/HttpServer.o"
	@echo "... src/HttpServer.i"
	@echo "... src/HttpServer.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/RequestHandler.o"
	@echo "... src/RequestHandler.i"
	@echo "... src/RequestHandler.s"
	@echo "... src/socket.o"
	@echo "... src/socket.i"
	@echo "... src/socket.s"
	@echo "... test/httpclienttest.o"
	@echo "... test/httpclienttest.i"
	@echo "... test/httpclienttest.s"
	@echo "... test/httprequesttest.o"
	@echo "... test/httprequesttest.i"
	@echo "... test/httprequesttest.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

